name: konsumer
description: "A Riverpod consumer for easier provider consumption"
version: 0.0.6
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  foundation:
    git:
      url: https://github.com/Order-of-Runes/foundation.git
      ref: 0.0.14
  konsumer_core:
    git:
      url: https://github.com/TheMakersPrime/konsumer_core.git
      ref: main
  statetris:
    git:
      url: https://github.com/TheMakersPrime/statetris.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0